apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: rig-prom
    url: http://127.0.0.1:13390
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
